### ISSUE TITLE
Avoid using a separate ws with manual ROS compilation for Python3 

### ISSUE THREAD

**Issue by marioney** [tud-cor/mc_mros_reasoner#26]
Create a singularity image with ROS Melodic version with Python3  to avoid creating a virtual environment.

**Comment by marioney** [comment]
> Create a singularity image with ROS Melodic version with Python3 to avoid creating a virtual environment.

This idea is not at good option so we can discard it.

I'm starting to test the [catkin_virtualenv](https://github.com/locusrobotics/catkin_virtualenv) and it seems promising, but it requires further testing.

**Comment by chcorbato** [comment]
> I'm starting to test the [catkin_virtualenv](https://github.com/locusrobotics/catkin_virtualenv) and it seems promising, but it requires further testing.

This has been implemented successfully in #85 , so issue solved.
