### ISSUE TITLE
update `master` branch for metacontrol_sim

### ISSUE THREAD

**Issue by chcorbato** [tud-cor/mc_mros_reasoner#68]
Currently is behind MVP_world

**Comment by marioney** [comment]
The MVP_world has been merged in https://github.com/rosin-project/metacontrol_sim/pull/48

@chcorbato  Do we need to update anything else?

**Comment by chcorbato** [comment]
Looks complete to me: #63 
We need to check with Nadia about the repo `rosin-experiments`
