### ISSUE TITLE
Standalone tests

### ISSUE THREAD

**Issue by chcorbato** [tud-cor/mc_mros_reasoner#84]
To test the metacontrol reasoner, we create "standalone" tests in `mc_mros_reasoner` pkg that only use:
- the reasoner node `mros1_reasoner.py`
- OWL files to load the KB
- monitoring input, mocked with diagnostic messages
(no reconfiguration infrastructure required).

`mros1_reasoner.py` is validated in each of the following tests by:
- successful run of the the MODELS20 experiments single script:
`[path_to_ws]/src/metacontrol_experiments (melodic)$ ./run_single_sim.sh -p 1 -g 1 -n "f1_v2_r2" -o 2 -r "true" -p 1.7 -c "false"`
- successful run of the test-specific execution of `mros1_reasoner.py`, meeting the expected test outcome.

**Potential outcomes**:
- The mros_reasoner keeps running or
- mros_reasoner stops at the following print (means that it is waiting for the reconfiguration action, but that requires the action server):
`[WARN] [...]: New Configuration requested: [...]`

### Test 1: 1-level functional architecture
Test that `mros1_reasoner.py` can load an owl file compliant with to tomasys including:
  - [x] a Function and multiple FDs that solve it
  - [x] QA performance values for the FDs

Test execution:
```
roslaunch mros1_reasoner run.launch onto:=/home/parallels/mros1_reasoner_ws/src/mros1_reasoner/mros1_reasoner/owl/test1.owl
```
**Expected outcome**:
The mros_reasoner keeps running without any errors or warnings, after initial self-explanatory warnings: 
```
started roslaunch server http://parallelsu18:38121/

SUMMARY
========

PARAMETERS
 * /onto_file: /home/parallels/m...
 * /rosdistro: melodic
 * /rosversion: 1.14.7

NODES
  /
    reasoner (mros1_reasoner/mros1_reasoner.py)

auto-starting new master
process[master]: started with pid [31908]
ROS_MASTER_URI=http://localhost:11311

setting /run_id to 51ac998c-f266-11ea-a2e5-001c42c03421
process[rosout-1]: started with pid [31922]
started core service [/rosout]
process[reasoner-2]: started with pid [31926]
* Owlready2 * Warning: optimized Cython parser module 'owlready2_optimized' is not available, defaulting to slower Python implementation
[INFO] [1599633186.932367]: Loaded ontology: /home/parallels/mros1_reasoner_ws/src/mros1_reasoner/mros1_reasoner/owl/test1.owl
[WARN] [1599633186.933808]: grounded_configuration not found in the param server
[INFO] [1599633186.934483]: KB initialization:
         - Supported QAs: 
                 - for Function f_navigate: /nfr_energy, /nfr_safety 
         - If an Objective instance is not found in the owl file, a default o_navigate is created.
[INFO] [1599633186.939409]: == FunctionDesigns available for obj: ['fd_print_1', 'fd_print_2']
[INFO] [1599633186.940081]: Objective NFR ENERGY: []
[WARN] [1599633186.940724]: == Objective has no NFRs, so a random FD is picked
[INFO] [1599633186.941390]: == FunctionDesigns also meeting NFRs: ['fd_print_1']
[INFO] [1599633186.942189]: > Best FD available fd_print_1
[WARN] [1599633186.942949]: Objective, NFRs and initial FG are generated from the OWL file
```

### Test 2: update FGs status from diagnostic messages (error status, QA values)
Deploy reasoner:
```
roslaunch mros1_reasoner run.launch onto:=/home/parallels/mros1_reasoner_ws/src/mros1_reasoner/mros1_reasoner/owl/test1.owl
```

  - [x] Test reception of `binding error` diagnostics (aka configuration in error) for `fg_o_print`:
```
rostopic pub /diagnostics diagnostic_msgs/DiagnosticArray "header:
  seq: 0
  stamp:
    secs: 0
    nsecs: 0
  frame_id: ''
status:
- level: 3
  name: 'fg_print'
  message: 'binding error'
  hardware_id: ''
  values:
  - {key: '', value: ''}" 
```

**Expected outcome**: result of the reasoning in the output of `mros_reasoner.py`, which halts after requesting a reconfiguration:
```
FGs:
fg_o_print      objective:  test1.o_print       status:  INTERNAL_ERROR         FD:  test1.fd_print_1   QAvalues:  []

OBJECTIVE       |  STATUS       |  NFRs
o_print         |   INTERNAL_ERROR      |   []
[WARN] [1599544843.736801]: Objectives in status ERROR: ['o_print']
[INFO] [1599544843.737571]:   >> Finished MAPE-K ** ANALYSIS **
[INFO] [1599544843.738258]:   >> Started MAPE-K ** PLAN adaptation **
[INFO] [1599544843.738992]: => Reasoner searches FD for objective: o_print
[INFO] [1599544843.740170]: == FunctionDesigns available for obj: ['fd_print_1', 'fd_print_2']
[INFO] [1599544843.742374]: Objective NFR ENERGY: []
[WARN] [1599544843.743381]: == Objective has no NFRs, so a random FD is picked
[INFO] [1599544843.744498]: == FunctionDesigns also meeting NFRs: ['fd_print_2']
[INFO] [1599544843.745680]: > Best FD available fd_print_2
[INFO] [1599544843.746622]:   >> Finished MAPE-K ** Plan adaptation **
[INFO] [1599544843.747609]:   >> Started MAPE-K ** EXECUTION **
[WARN] [1599544843.748801]: New Configuration requested: fd_print_2
```

### Test QA reception - fixed issue #92
- [x] Test reception of QA `performance` value:
```
rostopic pub /diagnostics diagnostic_msgs/DiagnosticArray "header:
  seq: 0
  stamp:
    secs: 0
    nsecs: 0
  frame_id: ''
status:
- level: 3
  name: 'fg_print'
  message: 'QA status'
  hardware_id: ''
  values:
  - {key: 'performance', value: '0.2'}" 
```
**Expected outcome**: result of the reasoning in the output of `mros_reasoner.py`
```
...
[WARN] [1599636741.649037]: QA value received for       fg_print        TYPE: performance       VALUE: 0.2
...
FGs:
fg_print        objective:  test1.o_print       status:  None   FD:  test1.fd_print_1   QAvalues:  [('performance', 0.2)]
```

# _TO COMPLETE_

### Test X: multi-level functional hierarchy
Test that `mros1_reasoner.py` can:
  - [ ] Hierarchical modellingA Function F1, a configuration FD1 that solves F1 and requires function F2, and a configuration FD2 that solves F2

Test execution:
```
```

**Comment by marioney** [comment]
The tests have been created in https://github.com/tud-cor/mc_mros_reasoner/commit/a1840915ea7707fbf404583abd4723ef115682f1

There are 3 different tests:

> Test 1: 1-level functional architecture

Checks the /rosout topic for the correct messages.

run it with
`rostest mros1_reasoner test_level_1_functional_arch.test`

> Test QA reception - fixed issue #92

Checks the /rosout topic for the correct messages (i.e. Message with received `performance` QA value of `0.2`

run it with
`rostest mros1_reasoner test_qa_reception.test `

**Test Models paper**

Test reconfiguration using parameters from the models paper.  Sends changing values of energy and safety and checks if the reasoner request a  reconfiguration action

run it with
`rostest mros1_reasoner test_models_paper.test`

The 3 tests are passing in the https://github.com/tud-cor/mc_mros_reasoner/tree/create_tests branch.  

@chcorbato  shoudl we merge this already?
