### ISSUE TITLE
Do not force parameters in the global scope / use absolute parameter names. This makes it impossible to namespace this `.launch` file.

### ISSUE THREAD

**Issue by chcorbato** [tud-cor/mc_mros_reasoner#86]
Please do not force parameters in the global scope / use absolute parameter names. This makes it impossible to namespace this `.launch` file.

_Originally posted by @gavanderhoorn in https://github.com/tud-cor/mc_mros_reasoner/pull/85#discussion_r484345340_

**Comment by marioney** [comment]
This is already solved in https://github.com/tud-cor/mc_mros_reasoner/commit/aace2aeb04854b373c16b40c82b9451fc58311b9

All parameters are now relative and inside the `<node>` tag
