### ISSUE TITLE
Local variable 'nfr_energy_value' referenced before assignment,  No such file or directory: 'kb.owl'

### ISSUE THREAD

**Issue by shreyashpalande** [tud-cor/mc_mros_reasoner#95]
Assign values to variables `nfr_energy_value` and `nfr_safety_value` in the `if condition` block

https://github.com/tud-cor/mc_mros_reasoner/blob/91667fab876b3fcdfb629def208d3ecf60583396/mros1_reasoner/scripts/mros1_reasoner.py#L77-L90

Use `default="$(find mros1_reasoner)/scripts/kb.owl"` as the file is not searched by ` default="kb.owl"`
https://github.com/tud-cor/mc_mros_reasoner/blob/91667fab876b3fcdfb629def208d3ecf60583396/mros1_reasoner/launch/run.launch#L3

No _test_mros1_reasoner.py_ available in the master branch

https://github.com/tud-cor/mc_mros_reasoner/blob/91667fab876b3fcdfb629def208d3ecf60583396/mros1_reasoner/launch/test.launch#L5

**Comment by marioney** [comment]
@shreyashpalande  thanks for reporting this.

These errors are fixed in https://github.com/tud-cor/mc_mros_reasoner/commit/44d3dab479426a1068ccf6da566c9929ed6a49c0

Can you check them, and if everything is OK close this
