### ISSUE TITLE
Remove import to owlread from main script

### ISSUE THREAD

**Issue by marioney** [tud-cor/mc_mros_reasoner#99]
This import

https://github.com/tud-cor/mc_mros_reasoner/blob/44d3dab479426a1068ccf6da566c9929ed6a49c0/mros1_reasoner/scripts/mros1_reasoner.py#L15

should not be needed,  as everything from that library should be in the tomasys.py file

**Comment by marioney** [comment]
I'm closing this as it's already solved in https://github.com/tud-cor/mc_mros_reasoner/commit/ef4d6f039139a6ef162a7ac71228a8617dff5020

**Comment by chcorbato** [comment]
https://twitter.com/erikras/status/1304887693575426048?s=21 @marioney 👏👏
